### ISSUE TITLE
GraphQL on the Beam

### ISSUE THREAD

**Issue by benwilson512** [graphql-erlang/graphql#46]
Hey!

I'm one of the authors of https://github.com/absinthe-graphql/absinthe, and am very excited to see interest in GraphQL within erlang as well.

I'm curious to know what has prompted you to develop your own implementation instead of using Absinthe. Is it purely a desire to not need an Elixir dependency? Does Absinthe seem very difficult to use from erlang? Did you simply want to take on the challenge?

**Comment by mrChex** [comment]
Hey.

Yes, I needed an implementation on pure Erlang. We have a requirement not to use dependencies with elixir and a great desire to try graphql in production. And how can I refuse such a challenge?

I have not tried to use absinthe yet, but soon I plan to compare this experience with erlang.

**Comment by benwilson512** [comment]
Fair enough, let me know if you run into any issues!
